x <- read.table("household_power_consumption.txt", sep = ";", na.strings = "?", stringsAsFactors = FALSE, header = TRUE)
x$dateTime <- paste(x$Date, x$Time)
x$dateTime <- paste(x$Date, x$Time)
x$dateTime <- as.POSIXct(strptime(x$dateTime, "%d/%m/%Y %H:%M:%S"))
mysub = subset(x, x$dateTime >= as.POSIXct('2007-2-1 00:00:00') & x$dateTime < as.POSIXct('2007-2-3 00:00:00'))
png("plot4.png", height = 480, width = 480, bg = "transparent" )
par(mfrow = c(2,2) )
plot(mysub$dateTime,mysub$Global_active_power,type= "l", ylab = "Global Active Power", xlab = "")
plot(mysub$dateTime, mysub$Voltage, type = "l", ylab = "Voltage", xlab = "datetime" )
with(mysub , plot(mysub$dateTime, mysub$Sub_metering_1, type = "n", ylab = "Energy sub metering", xlab = ""))
with(mysub, lines(mysub$dateTime, mysub$Sub_metering_1, col = "black" ))
with(mysub, lines(mysub$dateTime, mysub$Sub_metering_2, col = "red" ))
with(mysub, lines(mysub$dateTime, mysub$Sub_metering_3, col = "blue" ))
legend("topright",col = c("black", "red", "blue"), lty = 1, lwd = 2, legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3") )
plot(mysub$dateTime, mysub$Global_reactive_power, ylab = "Global_reactive_power", xlab = "datetime", type = "l")
dev.off()
